services:
  ros2:
    image: osrf/ros:iron-desktop-full
    environment:
      - DISPLAY=$DISPLAY
      - QT_GRAPHICSSYSTEM=native
      - QT_X11_NO_MITSHIM=1
      #user: 1000:1000
    container_name: ros2
    volumes:
      - .:/root/home/
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - $HOME/.Xauthority:/root/.Xauthority:ro
    network_mode: host
      #devices:
      #  - /dev/ttyUSB0:/dev/ttyUSB0
      #privileged: true
    cap_add:
      - NET_ADMIN
    tty: true
