services:
  ros2:
    #image: osrf/ros:jazzy-desktop-full
    #image: ros:jazzy
    build: .
    user: 1000:1000
    environment:
      - DISPLAY=$DISPLAY
      - QT_GRAPHICSSYSTEM=native
      - QT_X11_NO_MITSHIM=1
    volumes:
      - $HOME/:/home/ubuntu/home/
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - $HOME/.Xauthority:/root/.Xauthority:ro
    #devices:
    #  - /dev/ttyUSB0:/dev/ttyUSB0
    network_mode: host
    privileged: true
    tty: true
